data:
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

custom_reward_function:
  path: null
  name: compute_score

ray_init:
  timeline_json_file: null
